apiVersion: apps/v1
kind: Deployment
metadata:
  name: com-backend-app
  labels:
    apps: com-backend-app
spec:
  selector:
    matchLabels:
      app: com-backend-app
  replicas: 2
  template: 
    metadata:
      labels:
        app: com-backend-app
    spec:
      containers:
      - name: com-backend-app
        image: pratikshagourai/com-backend:latest
        ports: 
        - containerPort: 8080
